name: Daily update
on:
  schedule:
    - cron: '0 1 * * *'
permissions:
  contents: read
jobs:
  build-and-update:
    name: Daily Update
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - id: check
        name: Check byrdocs-logs-exporter release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: byrdocs
          repo: byrdocs-logs-exporter
      - name: Get byrdocs-logs-exporter binary
        run: |
          wget https://github.com/byrdocs/byrdocs-logs-exporter/releases/download/${{ steps.check.outputs.release }}/byrdocs-logs-exporter_${{ steps.check.outputs.release }}_x86_64-unknown-linux-musl.zip
          unzip byrdocs-logs-exporter_${{ steps.check.outputs.release }}_x86_64-unknown-linux-musl.zip byrdocs-logs-exporter
          chmod 777 byrdocs-logs-exporter
      - name: Run byrdocs-logs-exporter
        run: ./byrdocs-logs-exporter import "$(date -d 'yesterday' +'%Y-%m-%d')"
        env:
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
          R2_ANALYTICS_BUCKET: ${{ secrets.R2_ANALYTICS_BUCKET }}
          GRAFANA_DB_HOST: ${{ secrets.GRAFANA_DB_HOST }}
          GRAFANA_DB_PORT: ${{ secrets.GRAFANA_DB_PORT }}
          GRAFANA_DB_USERNAME: ${{ secrets.GRAFANA_DB_USERNAME }}
          GRAFANA_DB_PASSWORD: ${{ secrets.GRAFANA_DB_PASSWORD }}
          GRAFANA_DB_DATABASE: ${{ secrets.GRAFANA_DB_DATABASE }}
