name: Daily update
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build-and-update:
    name: Daily Update
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
      R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
      R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
      R2_ANALYTICS_BUCKET: ${{ secrets.R2_ANALYTICS_BUCKET }}
      LOGS_DB_HOST: ${{ secrets.LOGS_DB_HOST }}
      LOGS_DB_PORT: ${{ secrets.LOGS_DB_PORT }}
      LOGS_DB_USERNAME: ${{ secrets.LOGS_DB_USERNAME }}
      LOGS_DB_PASSWORD: ${{ secrets.LOGS_DB_PASSWORD }}
      LOGS_DB_DATABASE: ${{ secrets.LOGS_DB_DATABASE }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - id: check
        name: Check byrdocs-logs-exporter release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: byrdocs
          repo: byrdocs-logs-exporter
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get byrdocs-logs-exporter binary
        run: |
          wget https://github.com/byrdocs/byrdocs-logs-exporter/releases/download/${{ steps.check.outputs.release }}/byrdocs-logs-exporter_${{ steps.check.outputs.release }}_x86_64-unknown-linux-musl.zip
          unzip byrdocs-logs-exporter_${{ steps.check.outputs.release }}_x86_64-unknown-linux-musl.zip byrdocs-logs-exporter
          chmod 777 byrdocs-logs-exporter
      - name: Run byrdocs-logs-exporter
        run: ./byrdocs-logs-exporter import "$(date -d 'yesterday' +'%Y-%m-%d')"
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 30
        with:
          #sudo: false
          limit-access-to-actor: true
